### ISSUE TITLE
Missing Middleware for Proof-of-Authority Chains in Ape Polygon Plugin

### ISSUE THREAD

**Issue by moses966** [ApeWorX/ape-polygon#33]
---

#### Description:
I encountered an error while trying to use the ApeWorx Polygon plugin. The error message suggests that the plugin is not handling Proof-of-Authority (POA) chains properly due to missing middleware.

#### Error Details:
```lua
(BlockNotFoundError) Missing latest block. 
Reason: The field extraData is 100 bytes, but should be 32. 
It is quite likely that you are connected to a POA chain. 
Refer to http://web3py.readthedocs.io/en/stable/middleware.html#proof-of-authority
```

The error seems to indicate that the necessary middleware for handling POA chains has not been injected correctly.

#### Steps to Reproduce:
1. Install the ApeWorx Polygon plugin using `pip install ape-polygon`.
2. Attempt to connect to the Polygon network using the plugin by running:
   `ape run deploy --network polygon:amoy:alchemy`
3. Observe the error when fetching the latest block.

#### Expected Behavior:
The plugin should inject the necessary middleware to handle POA chains, similar to what Web3.py’s middleware does for POA networks.

#### Actual Behavior:
The plugin fails with a `BlockNotFoundError` due to the `extraData` field being 100 bytes instead of the expected 32 bytes, indicating missing middleware support for POA chains.

#### Environment:
- **eth-ape**: `0.8.15`
- **ape-polygon**:` 0.8.0`
- **Python Version**: `3.10.12`
- **Operating System**: `Ubuntu 22.04.4 LTS`

#### Additional Context:
The error occurs when interacting with a Proof-of-Authority chain like Polygon. According to the Web3.py documentation, the missing middleware should handle the `extraData` field for POA networks by adjusting its size appropriately.

Thank you for looking into this!

---

**Comment by bitwise-constructs** [comment]
Might need to wait on 0.9 as this requires web3.py v7

**Comment by moses966** [comment]
Hi @bitwise-constructs ,
Did you mean waiting on eth-ape version `0.9`?

**Comment by bitwise-constructs** [comment]
@moses966 correct, the current 0.9 branch raises a lot of pins including web3 https://github.com/ApeWorX/ape/tree/feat/0-9

**Comment by antazoey** [comment]
The issue is actually in the provider (ape-alchemy):

https://github.com/ApeWorX/ape-alchemy/blob/main/ape_alchemy/provider.py#L116-L122

**Comment by antazoey** [comment]
amoy's chain ID just needs to be added to that list.

**Comment by antazoey** [comment]
Also, we should make `ape-alchemy` behave like `ape-node` where if it encounters this error, it will automatically add the middleware as well:

https://github.com/ApeWorX/ape/blob/main/src/ape_ethereum/provider.py#L1511-L1530

**Comment by moses966** [comment]
> The issue is actually in the provider (ape-alchemy):
> 
> https://github.com/ApeWorX/ape-alchemy/blob/main/ape_alchemy/provider.py#L116-L122

Quicknode too
